theme = "hugo-theme-windicss-starter"
languageCode = "en-us"
baseurl = "https://example.com/"
title = "Hugo UnoCSS Starter"

author = "Mark Jones"
copyright = "Copyright © 2021, Mark Jones, all rights reserved."

[params]
    name = "Hugo UnoCSS Starter"
    description = "A simple bootstraped theme for Hugo, build with UnoCSS."

    github_user = "taocode"
    github_repo = "https://github.com/taocode/hugo-theme-windicss-starter"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true
