[build]
  base = "themes/hugo-theme-windicss-starter/exampleSite"
  publish = "themes/hugo-theme-windicss-starter/exampleSite/public"
  command = "npm i && npm build:example"

[build.environment]
  HUGO_VERSION = "0.80.0"